### ISSUE TITLE
vocab.txt is lost

### ISSUE THREAD

**Issue by bruce1408** [GuidoPaul/CAIL2019#3]
```File "/home/user/anaconda3/envs/pytorch_cuda_10/lib/python3.6/site-packages/pytorch_pretrained_bert/tokenization.py", line 96, in __init__
    "model use `tokenizer = 

BertTokenizer.from_pretrained(PRETRAINED_MODEL_NAME)`".format(vocab_file))
ValueError: Can't find a vocabulary file at path 'output/ckpts/vocab.txt'. To load the vocabulary from a Google pretrained model use `tokenizer = BertTokenizer.from_pretrained(PRETRAINED_MODEL_NAME)`
```
ValueError: Can't find a vocabulary file at path 'output/ckpts/vocab.txt'. To load the vocabulary from a Google pretrained model use `tokenizer = BertTokenizer.from_pretrained(PRETRAINED_MODEL_NAME)`
**无法找到output/ckpts/vocab.txt**词典文件，这个文件是 ms 中下载的那个吗?
我用官网下载的ms下面的vocab.txt 文件内容如下：
```
[PAD]
[unused1]
[unused2]
[unused3]
[unused4]
[unused5]
[unused6]
[unused7]
[unused8]
[unused9]
[unused10]
[unused11]
[unused12]
[unused13]
...
```
感觉这个文件 ms/vocab.txt文件并不是 **output/ckpts/vocab.txt**的文件，您可以提供以下这个文件吗？谢谢

**Comment by huangyanzhou163** [comment]
i have already copied the ms/vocab.txt and ms/config.json to the output/ckpts/. And it turns out the the result is rather negative.
datasets/bigfolds/fold2_valid.txt
[2019-11-04 16:27:17]: bert tester.py[line:76] INFO  min: -0.0000 max: 0.0000 avg: 0.0000 loss: 1.0000 acc: 237, 0.4647
Took  0 min 29 sec

**Comment by bruce1408** [comment]
> i have already copied the ms/vocab.txt and ms/config.json to the output/ckpts/. And it turns out the the result is rather negative.
> datasets/bigfolds/fold2_valid.txt
> [2019-11-04 16:27:17]: bert tester.py[line:76] INFO min: -0.0000 max: 0.0000 avg: 0.0000 loss: 1.0000 acc: 237, 0.4647
> Took 0 min 29 sec

when i can not find the  file, i am similar to youts, to copy the ms/vocab.txt to /ckpts/ path; and almost the same result; 
```
---------- Bert Eval ... ----------
datasets/bigfolds/fold2_valid.txt
[2019-11-04 21:03:00]: bert tester.py[line:76] INFO  min: -0.0034 max: 0.0019 avg: 0.0000 loss: 1.0000 acc: 242, 0.4745
Took  0 min 18 sec
```

**Comment by GuidoPaul** [comment]
1. `vocab.txt`文件一直是同一份文件，是ms里包含的`vocab.txt`文件，存放在“models/ms/"文件夹里
2. finetune模型在`train_bert.py`文件中完成，finetune的模型文件保存在"output/ckpts/"
3. `main.py`文件负责结果的测试，测试前需要手动把“models/ms/“的`bert_config.json`、`vocab.txt`复制到“output/ckpts/”，同时`bert_config.json`需要重命名为`config.json`

**Comment by bruce1408** [comment]
> 1. `vocab.txt`文件一直是同一份文件，是ms里包含的`vocab.txt`文件，存放在“models/ms/"文件夹里
> 2. finetune模型在`train_bert.py`文件中完成，finetune的模型文件保存在"output/ckpts/"
> 3. `main.py`文件负责结果的测试，测试前需要手动把“models/ms/“的`bert_config.json`、`vocab.txt`复制到“output/ckpts/”，同时`bert_config.json`需要重命名为`config.json`
